### ISSUE TITLE
Modify CWE-1206 Category Name - Include phrase "or Semiconductor Defects"

### ISSUE THREAD

**Issue by BobH-MITRE** [CWE-CAPEC/hw-cwe-sig#1]
A sig member has suggested that the category CWE-1206 name should be changed from "Power, Clock, Thermal, Reset Concerns" to "Power, Clock, Thermal, Reset Concerns, **and Semiconductor Defects**." The rationale is this: The current title does not discuss hardware deterioration. So we should add something like that.

(Internal Tracker #731)

**Comment by BobH-MITRE** [comment]
Bob -

I'm OK with adding Semiconductor Defects; yet the title should use "or" rather than "and" in "Power, Clock, Thermal, Reset Concerns and Semiconductor Defects". Remember, using "and" implies it has to be all those conditions; yet using "or" means only one of the issues needs to be relevant to the specific weakness to be under this CWE.

...Joe

**Comment by jmfung55** [comment]
Here is the context to keep in mind.  

•	We already have a category called Manufacturing and Life Cycle Management Concerns (1195) which covers "defects that arise in the semiconductor-manufacturing process or during the life cycle and supply chain".  
•	One of the existing entries is "Semiconductor Defects in Hardware Logic with Security-Sensitive Implications" (1248).  

•	It was proposed to add 1248 to "Power, Clock, Thermal, Reset Concerns" (1206) because "CWE-1248 makes reference to thermal/electrical stress”.  
•	Now we say we should expand 1206 with "Manufacturing Defects" because the category "does not talk about hardware deterioration at all".  


If we follow the thought process, the next proposal is likely to be combining both categories 1195 and 1206 together into one.   I am not sure it helps to navigate our collaterals with larger categories.

**Comment by BobH-MITRE** [comment]
Had a discussion on this topic at the SIG call today. In light of Defects being covered by another category, we have agreed that this is not something we should move forward with.  Closing issue.
